- name: "Replace Node"
  hosts: 172.31.0.102
  become: True
  tasks:

    - name: "Stop ScyllaDB"
      ansible.builtin.systemd_service:
        name: scylla-server.service
        state: stopped

    - name: Wipe data-dir
      ansible.builtin.shell:
        cmd: 'rm -fr /var/lib/scylla/data/* ;  find /var/lib/scylla -type f -delete'
